### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by AntonMezger** [derhansen/extbase_bemodule_ajax#1]
Nice,

would it be possible to adapt this to typo3 11 for uploading a file with a progress bar and at the end of the process implement php for writing the information to a database with typo3 code?

would be awesome, while this kind of implementation does not exist in typo3 

Kind regards

Anton

**Comment by derhansen** [comment]
The technique shown in this repository is 10 years old. Do not use it or do not even try to adapt it to TYPO3 11 or later, since nothing of this is future proof any more.

The TYPO3 core has an API to display a progressbar (nprogress) in backend modules. See this https://github.com/TYPO3/typo3/blob/main/Build/Sources/TypeScript/extensionmanager/update.ts as an example on how to use it.
